# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://81.71.33.11:3306/yumeng_ry?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 8ebc82c3d3535489
    driver-class-name: com.mysql.cj.jdbc.Driver

  # redis 配置
  redis:
    # 地址
    host: 81.71.33.11
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 1p3l3r0GvVkH
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
