

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8089

spring:
  profiles:
    active: dev


## 日志配置
#logging:
#  level:
#    com.fish: debug
#    org.springframework: info
#  config: classpath:logback.xml

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.fish.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml


# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*,/doc.html
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 开启控制台日志打印
logging:
  level:
    com.fish.flowfront.mapper: debug

